<?php

namespace TYPO3\FLOW3\Persistence\Doctrine\Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class TYPO3CoSADomainModelAnswerProxy extends \TYPO3\CoSA\Domain\Model\Answer implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
            if (is_callable(array($this, '__wakeup'))) {
                $this->__wakeup();
            }
        }
    }
    
    
/**
	 * Autogenerated Proxy Method
	 */
    public function __wakeup()
    {
        $this->__load();
        return parent::__wakeup();
    }

/**
	 * Autogenerated Proxy Method
	 */
    public function FLOW3_AOP_Proxy_invokeJoinPoint(\TYPO3\FLOW3\AOP\JoinPointInterface $joinPoint)
    {
        $this->__load();
        return parent::FLOW3_AOP_Proxy_invokeJoinPoint($joinPoint);
    }

/**
	 * Get the Route
	 *
	 * @return TYPO3\CoSA\Domain\Model\Route The Route
	 */
    public function getRoute()
    {
        $this->__load();
        return parent::getRoute();
    }

/**
	 * Sets this Route
	 *
	 * @param TYPO3\CoSA\Domain\Model\Route $route The Route
	 * @return void
	 */
    public function setRoute($route)
    {
        $this->__load();
        return parent::setRoute($route);
    }

/**
	 * Get the Question
	 *
	 * @return TYPO3\CoSA\Domain\Model\Question The Question
	 */
    public function getQuestion()
    {
        $this->__load();
        return parent::getQuestion();
    }

/**
	 * Sets this Question
	 *
	 * @param TYPO3\CoSA\Domain\Model\Question $question The Question
	 * @return void
	 */
    public function setQuestion($question)
    {
        $this->__load();
        return parent::setQuestion($question);
    }

/**
	 * Get the Answer's text
	 *
	 * @return string The Answer's text
	 */
    public function getText()
    {
        $this->__load();
        return parent::getText();
    }

/**
	 * Sets this Answer's text
	 *
	 * @param string $text The Answer's text
	 * @return void
	 */
    public function setText($text)
    {
        $this->__load();
        return parent::setText($text);
    }


    public function __sleep()
    {
        return array_merge(array('__isInitialized__'), parent::__sleep());
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        parent::__clone();
    }
}