<?php

namespace TYPO3\FLOW3\Persistence\Doctrine\Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class TYPO3CoSADomainModelQuestionProxy extends \TYPO3\CoSA\Domain\Model\Question implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
            if (is_callable(array($this, '__wakeup'))) {
                $this->__wakeup();
            }
        }
    }
    
    
/**
	 * Autogenerated Proxy Method
	 */
    public function __wakeup()
    {
        $this->__load();
        return parent::__wakeup();
    }

/**
	 * Autogenerated Proxy Method
	 */
    public function FLOW3_AOP_Proxy_invokeJoinPoint(\TYPO3\FLOW3\AOP\JoinPointInterface $joinPoint)
    {
        $this->__load();
        return parent::FLOW3_AOP_Proxy_invokeJoinPoint($joinPoint);
    }

/**
	 * Get the Room
	 *
	 * @return TYPO3\CoSA\Domain\Model\Room The Room
	 */
    public function getRoom()
    {
        $this->__load();
        return parent::getRoom();
    }

/**
	 * Sets this Room
	 *
	 * @param TYPO3\CoSA\Domain\Model\Room $room The Room
	 * @return void
	 */
    public function setRoom($room)
    {
        $this->__load();
        return parent::setRoom($room);
    }

/**
	 * Get the Answer
	 *
	 * @return TYPO3\CoSA\Domain\Model\Answer The Answer
	 */
    public function getAnswer()
    {
        $this->__load();
        return parent::getAnswer();
    }

/**
	 * Sets this Answer
	 *
	 * @param TYPO3\CoSA\Domain\Model\Answer $answer The Answer
	 * @return void
	 */
    public function setAnswer($answer)
    {
        $this->__load();
        return parent::setAnswer($answer);
    }

/**
	 * Get the Question's text
	 *
	 * @return string The Question's text
	 */
    public function getText()
    {
        $this->__load();
        return parent::getText();
    }

/**
	 * Sets this Question's text
	 *
	 * @param string $text The Question's text
	 * @return void
	 */
    public function setText($text)
    {
        $this->__load();
        return parent::setText($text);
    }


    public function __sleep()
    {
        return array_merge(array('__isInitialized__'), parent::__sleep());
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        parent::__clone();
    }
}