<?php

namespace TYPO3\FLOW3\Persistence\Doctrine\Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class TYPO3FLOW3MVCWebRoutingObjectPathMappingProxy extends \TYPO3\FLOW3\MVC\Web\Routing\ObjectPathMapping implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
            if (is_callable(array($this, '__wakeup'))) {
                $this->__wakeup();
            }
        }
    }
    
    
/**
	 * Autogenerated Proxy Method
	 */
    public function __wakeup()
    {
        $this->__load();
        return parent::__wakeup();
    }

/**
	 * Autogenerated Proxy Method
	 */
    public function FLOW3_AOP_Proxy_invokeJoinPoint(\TYPO3\FLOW3\AOP\JoinPointInterface $joinPoint)
    {
        $this->__load();
        return parent::FLOW3_AOP_Proxy_invokeJoinPoint($joinPoint);
    }

/**
	 * @param string $pathSegment
	 */
    public function setPathSegment($pathSegment)
    {
        $this->__load();
        return parent::setPathSegment($pathSegment);
    }

/**
	 * @return string
	 */
    public function getPathSegment()
    {
        $this->__load();
        return parent::getPathSegment();
    }

/**
	 * @param string $uriPattern
	 */
    public function setUriPattern($uriPattern)
    {
        $this->__load();
        return parent::setUriPattern($uriPattern);
    }

/**
	 * @return string
	 */
    public function getUriPattern()
    {
        $this->__load();
        return parent::getUriPattern();
    }

/**
	 * @param string $identifier
	 */
    public function setIdentifier($identifier)
    {
        $this->__load();
        return parent::setIdentifier($identifier);
    }

/**
	 * @return string
	 */
    public function getIdentifier()
    {
        $this->__load();
        return parent::getIdentifier();
    }

/**
	 * @param string $objectType
	 */
    public function setObjectType($objectType)
    {
        $this->__load();
        return parent::setObjectType($objectType);
    }

/**
	 * @return string
	 */
    public function getObjectType()
    {
        $this->__load();
        return parent::getObjectType();
    }


    public function __sleep()
    {
        return array_merge(array('__isInitialized__'), parent::__sleep());
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        parent::__clone();
    }
}