<?php
namespace TYPO3\FLOW3\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120112174831 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE cosa_domain_model_answer (flow3_persistence_identifier VARCHAR(40) NOT NULL, question VARCHAR(40) DEFAULT NULL, text VARCHAR(255) DEFAULT NULL, points INT DEFAULT NULL, INDEX IDX_6FCBBE1FB6F7494E (question), PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE cosa_domain_model_question (flow3_persistence_identifier VARCHAR(40) NOT NULL, text VARCHAR(255) DEFAULT NULL, PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("ALTER TABLE cosa_domain_model_answer ADD CONSTRAINT FK_6FCBBE1FB6F7494E FOREIGN KEY (question) REFERENCES cosa_domain_model_question(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE typo3_party_domain_model_person DROP FOREIGN KEY FK_C60479E121E3D446");
		$this->addSql("ALTER TABLE typo3_party_domain_model_person ADD CONSTRAINT FK_C60479E121E3D446 FOREIGN KEY (flow3_persistence_identifier) REFERENCES typo3_party_domain_model_abstractparty(flow3_persistence_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE cosa_domain_model_room DROP firstanswer, DROP secondanswer, CHANGE question question VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE cosa_domain_model_room ADD CONSTRAINT FK_454D5EA1B6F7494E FOREIGN KEY (question) REFERENCES cosa_domain_model_question(flow3_persistence_identifier)");
		$this->addSql("CREATE UNIQUE INDEX UNIQ_454D5EA1B6F7494E ON cosa_domain_model_room (question)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE cosa_domain_model_answer DROP FOREIGN KEY FK_6FCBBE1FB6F7494E");
		$this->addSql("ALTER TABLE cosa_domain_model_room DROP FOREIGN KEY FK_454D5EA1B6F7494E");
		$this->addSql("DROP TABLE cosa_domain_model_answer");
		$this->addSql("DROP TABLE cosa_domain_model_question");
		$this->addSql("ALTER TABLE cosa_domain_model_room DROP FOREIGN KEY FK_454D5EA1B6F7494E");
		$this->addSql("DROP INDEX UNIQ_454D5EA1B6F7494E ON cosa_domain_model_room");
		$this->addSql("ALTER TABLE cosa_domain_model_room ADD firstanswer VARCHAR(255) DEFAULT NULL, ADD secondanswer VARCHAR(255) DEFAULT NULL, CHANGE question question VARCHAR(255) DEFAULT NULL");
		$this->addSql("ALTER TABLE typo3_party_domain_model_person DROP FOREIGN KEY FK_C60479E121E3D446");
		$this->addSql("ALTER TABLE typo3_party_domain_model_person ADD CONSTRAINT FK_C60479E121E3D446 FOREIGN KEY (flow3_persistence_identifier) REFERENCES typo3_party_domain_model_abstractparty(flow3_persistence_identifier)");
	}
}

?>